# Generated by Django 3.0.5 on 2020-04-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=2)),
            ],
        ),
    ]
